### ISSUE TITLE
missing data - Test limits?

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#38]
<=beta6

When you click the Test button to view the WFS data set you are working with, does that view of the data only return 500 records max?  suspect this is the case.

![image](https://user-images.githubusercontent.com/26335003/93507230-39841700-f8d2-11ea-850d-6e1c5c469de0.png)

If that is true then we should put a warning to users  (note 500 feature limit in Test view):

![image](https://user-images.githubusercontent.com/26335003/93507445-8e279200-f8d2-11ea-8df2-5c233ede84ca.png)

If that the case only with Geoserver based layers?

**Comment by qqnluaq** [comment]
The request you are using in the app is:
`http://openmaps.gov.bc.ca/geo/ows?service=WFS&version=2.0&request=GetFeature&typeName=pub:WHSE_IMAGERY_AND_BASE_MAPS.GSR_SCHOOLS_K_TO_12_SVW&outputFormat=application/json&srsname=EPSG:4326`

which is correct but the geoserver limits these getFeature requests to a max of 500 features. There is a parameter `count` that can passed to request to control the number of features to return, but it seems to be capped at 500. There is also a `startIndex` parameter so that additional pages of data can be retrieved, but this requires that the features be ordered in a well-defined way, so additional parameters are required to specify the key and how to order it. This gets complicated.

I found an alternative way to make this request that bypasses this limit:
`https://openmaps.gov.bc.ca/geo/pub/WHSE_IMAGERY_AND_BASE_MAPS.GSR_SCHOOLS_K_TO_12_SVW/ows?service=WMS&request=GetMap&version=1.1.1&layers=pub%3AWHSE_IMAGERY_AND_BASE_MAPS.GSR_SCHOOLS_K_TO_12_SVW&styles=3601&format=application/json;type=geojson&transparent=true&cql_filter=include&srs=EPSG%3A4326&width=645&height=728&bbox=-131.8579103,46.6645175,-117.6855469,56.547372`

This returns the full set of all the features in one request.
I suggest using this form of request for the initial release. Supporting WFS properly will require some additional work in SMK.

**Comment by NicoledeGreef** [comment]
Francophone draft site layers have been converted to WMS/json calls instead of WFS.
