### ISSUE TITLE
smk-cli on screen instructions issue

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-cli#54]
New user was trying to use the smk-cli and was tripped up by reference to 'index' as a command.

![image](https://user-images.githubusercontent.com/26335003/98144088-cb45e480-1e7e-11eb-85f9-fb6ab9f64980.png)

![image](https://user-images.githubusercontent.com/26335003/98144211-f92b2900-1e7e-11eb-8a23-f4ea6a2b5dc8.png)

**Comment by michaelpnelson** [comment]
The word "index" is not hard-coded in the output seen when an smk-cli command is first run; instead, it's a variable that is based on the command that was entered. For example, when the command "smk edit" is run, code in index.js parses the command arguments and this logic should result in "smk" being used in the output instead of "index" as seen in the screen captures.

If it's at all possible, it would be great to know what command was entered by the first-time user when this behaviour was observed. I'd also be curious to know whether the user sees this behaviour all the time. @NicoledeGreef , please let me know what you think.

**Comment by NicoledeGreef** [comment]
@TerryLanktree initially reported this.  He didn't know to run **smk** **create** so he just typed in smk and hit return.  If  do that I see the same mention of 'index':
![image](https://user-images.githubusercontent.com/26335003/134049109-6a368fe0-abe9-405e-8c13-e027efa35687.png)

It's not a bug that makes the product non-functional.  He just got confused by 'index' next to the listing of valid arguments.

**Comment by michaelpnelson** [comment]
This issue has been addressed in pull request https://github.com/bcgov/smk-cli/pull/79, and changes have been merged to master.
